#!/usr/bin/python

import socket
import time

MTU = 512

if __name__ == "__main__":
    UDP_IP = "127.0.0.1"
    UDP_PORT = 5005
    print "UDP target IP:", UDP_IP
    print "UDP target port:", UDP_PORT

    sock = socket.socket(socket.AF_INET, # Internet
                         socket.SOCK_DGRAM) # UDP

    f = open("/home/zasimov/tmp/videos/rtp.mp4", "rb")
    n = 0
    while True:
        buf = f.read(MTU)
        if not buf:
            break
        sock.sendto(buf, (UDP_IP, UDP_PORT)) 
	time.sleep(1)
        print "packet %s" % n
        n += 1

    f.close()

